IF NOT EXISTS (SELECT TOP 1 * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'R_Cars' AND TABLE_SCHEMA = 'dbo')
BEGIN
    CREATE TABLE R_Cars (
    Id INT PRIMARY KEY IDENTITY (1, 1),
    AggregateId UNIQUEIDENTIFIER  NOT NULL,
    Brand NVARCHAR (64) NOT NULL,
    Model NVARCHAR (255) NOT NULL,
    Year INT NOT NULL
);
END