apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage-write-temp
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage-write-temp-pv
  labels:
    type: local-storage-write-temp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-write-temp
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  local: #c:\temp\write-logs
    path: /run/desktop/mnt/host/c/temp/write-logs
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - docker-desktop

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-storage-write-temp-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-write-temp
  resources:
    requests:
      storage: 1Gi