IF NOT EXISTS (SELECT TOP 1 * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'W_Cars' AND TABLE_SCHEMA = 'dbo')
BEGIN
    CREATE TABLE W_Cars (
        Id INT PRIMARY KEY IDENTITY (1, 1),
        AggregateId UNIQUEIDENTIFIER  NOT NULL,
        Command NVARCHAR (64) NOT NULL,
        Payload NVARCHAR (MAX) NOT NULL
    );
END